# Generated by Django 2.2.13 on 2020-11-24 11:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='WidgetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
                ('template_name', models.CharField(blank=True, default='widgets/widget.html', max_length=200, null=True, verbose_name='template name')),
                ('context', models.TextField(blank=True, help_text='Use the JSON syntax.', null=True, validators=[core.models.validate_json], verbose_name='context')),
                ('public', models.BooleanField(default=True, verbose_name='public?')),
            ],
            options={
                'verbose_name': 'widget template',
                'verbose_name_plural': 'widget templates',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('context', models.TextField(blank=True, help_text='Use the JSON syntax.', null=True, validators=[core.models.validate_json], verbose_name='context')),
                ('show_title', models.BooleanField(default=True, verbose_name='show title')),
                ('editable', models.BooleanField(default=False, verbose_name='editable')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='widgets', to='widgets.Region', verbose_name='region')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instances', to='widgets.WidgetTemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'widget',
                'verbose_name_plural': 'widgets',
                'ordering': ('region', 'sort_order', 'title'),
            },
        ),
    ]
